# Generated by Django 6.0.3 on 2026-04-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
