# Generated by Django 6.0.3 on 2026-04-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash on Delivery'), ('Online', 'Online Payment')], default='Cash', max_length=20),
        ),
    ]
